name: ESLint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: cd appointments; yarn
      - name: Run tests
        run: cd appointments; yarn eslint
